### PR TITLE
chore: add devcontainer config

### PR DESCRIPTION
**Pull request by yocjyet**
It is difficult to develop without correct environment configuration, so GitHub's Codespaces or VSCode's devcontainer could be a good start point. This PR attempts to add a devcontainer config to install required dependencies wether in system or in each languages, utilsing Docker, Nix and devenv.

### CODE REVIEW

**Comment by borh** [comment]
I may as well merge this as I have no experience with using devcontainers...
One issue is that if we continue using devenv, we may want to use the built-in devcontainers support:

Doing so now will generate a .devcontainer.json like so:

```json
{
  "customizations": {
    "vscode": {
      "extensions": [
        "mkhl.direnv"
      ]
    }
  },
  "image": "ghcr.io/cachix/devenv:latest",
  "overrideCommand": false,
  "updateContentCommand": "devenv test"
}
```

But maybe we just merge this with the current version?

Note that we may want to use a different base image (let's say uv's official images such as ghcr.io/astral-sh/uv:python3.12-bookworm-slim or similar), as dealing with native Python deps may not be easy using nix.

**Comment by borh** [comment]
I've added a new flake that seems to work for both backend and frontend.

**Review by borh — APPROVED** [review]
LGTM

**Comment by yocjyet** [comment]
For some reason direnv is not still working as expected even if I modified the ".envrc" file, but at least I have successfully installed it.

**Comment by yocjyet** [comment]
The dev environment itself is working as expected and both Python and JavaScript environment seem to work fine. The document can be updated later.

**Pull request merged**
